apiVersion: v1
kind: Service
metadata:
  labels:
    app: influx-service
  name: influx-service
spec:
  type: ClusterIP
  selector:
    app: influx-pod
  ports:
  - name: influx-ports
    protocol: TCP
    port: 8086
    targetPort: 8086
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: influx-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: "/var/lib/influxdb"
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influx-pvc
  labels:
    app: influx-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: influx-deployment
  labels:
    app: influx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influx-pod
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: influx-pod
    spec:
      restartPolicy: Always
      containers:
      - image: my_influxdb
        name: influxdb
        imagePullPolicy: Never
        ports:
        - containerPort: 8086
        volumeMounts:
        - name: influx-pvc
          mounthPath: /var/lib/influxdb
      volumes:
      - name: influx-pvc
        persistentVolumeClaim:
          claimName: influx-pvc
