#!/bin/sh

tmp_file='mktemp'
if [ ! -f $tmp_file ]; then 
	return 1
fi

echo "CREATE USER '$MYSQL_DB_USER'@' IDENTIFIED BY '$MYSQL_DB_PWD';" >> $tmp_file
cat <<EOF > $tmp_file
RENAME USER 'mysql'@'localhost' to '$MYSQL_ADMIN'@'localhost';
SET PASSWORD FOR '$MYSQL_ADMIN'@'localhost'=PASSWORD('${MYSQL_ADMIN_PWD}');
GRANT ALL ON *.* TO '$MYSQL_ADMIN'@'0.0.0.0' IDENTIFIED BY '$MYSQL_ADMIN_PWD' WITH GRANT OPTION;
GRANT ALL ON *.* TO '$MYSQL_ADMIN'@'localhost' IDENTIFIED BY '$MYSQL_ADMIN_PWD' WITH GRANT OPTION;

CREATE DATABASE IF NOT EXISTS $MYSQL_BD_NAME CHARACTER SET utf8 COLLATE utf8_general_ci;

GRANT ALL ON $MYSQL_BD_NAME.* TO '$MYSQL_DB_USER'@'%' IDENTIFIED BY '$MYSQL_DB_PWD' WITH GRANT OPTION;
GRANT ALL ON $MYSQL_BD_NAME.* TO '$MYSQL_DB_USER'@'0.0.0.0' IDENTIFIED BY '$MYSQL_DB_PWD' WITH GRANT OPTION;
GRANT ALL ON $MYSQL_BD_NAME.* TO '$MYSQL_DB_USER'@'localhost' IDENTIFIED BY '$MYSQL_DB_PWD' WITH GRANT OPTION;
DROP DATABASE test;
FLUSH PRIVILEGES;
EOF

mysql < $tmp_file
rm $tmp_file
exit
