FLUSH PRIVILEGES;
CREATE DATABASE wordpress;
CREATE USER 'agarzon'@'%' IDENTIFIED BY 'agarzon';
GRANT ALL PRIVILIGES ON *.* TO 'agarzon'@'%' WITH GRANT OPTION;
USE wordpress;
DROP DATABASE test;
FLUSH PRIVILEGES;
