FLUSH PRIVILEGES;
CREATE DATABASE wordpress;
CREATE USER 'agarzon'@'%' IDENTIFIED BY 'agarzon';
GRANT ALL PRIVILEGES ON `wordpress`.* TO 'agarzon'@'%' IDENTIFIED BY 'agarzon' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `wordpress`.* TO 'agarzon'@'localhost' IDENTIFIED BY 'agarzon' WITH GRANT OPTION;
DROP DATABASE test;
FLUSH PRIVILEGES;
