apiVersion: v1
kind: Service
metadata:
  labels:
    app: mysql-service
  name: mysql-service
spec:
  type: ClusterIP
  selector:
    app: mysql-pod
  ports:
  - name: mysql-ports
    protocol: TCP
    port: 3306
    targetPort: 3306
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    app: mysql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-pod
  template:
    metadata:
      labels:
        app: mysql-pod
    spec:
      containers:
      - image: my_sql
        name: mysql
        imagePullPolicy: Never
        ports:
        - containerPort: 3306
          name: mysql-cont-port
        env:
          - name: MYSQL_DB_NAME
            valueFrom:
              secretKeyRef:
                name: wp-mysql-php-secret
                key: wordpress-db-name
          - name: MYSQL_DB_USER
            valueFrom:
              secretKeyRef:
                name: wp-mysql-php-secret
                key: mysql-db-user
          - name: MYSQL_DB_PWD
            valueFrom:
              secretKeyRef:
                name: wp-mysql-php-secret
                key: mysql-db-pwd
          - name: MYSQL_ADMIN
            valueFrom:
              secretKeyRef:
                name: wp-mysql-php-secret
                key: mysql-admin
          - name: MYSQL_ADMIN_PWD
            valueFrom:
              secretKeyRef:
                name: wp-mysql-php-secret
                key: mysql-admin-pwd
      restartPolicy: Always

