apiVersion: v1
kind: Service
metadata:
  labels:
    app: mysql-service
  name: mysql-service
spec:
  type: ClusterIP
  selector:
    app: mysql-pod
  ports:
  - name: mysql-ports
    protocol: TCP
    port: 3306
    targetPort: 3306
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: "/var/lib/mysql"
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  labels:
    app: mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    app: mysql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-pod
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mysql-pod
    spec:
      restartPolicy: Always
      containers:
      - image: my_sql
        name: mysql
        imagePullPolicy: Never
        env:
        - name: MYSQL_PWD
          valueFrom:
            secretKeyRef:
              name: wp-mysql-php-secret
              key: mysql-db-pwd
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: wp-mysql-php-secret
              key: mysql-db-user
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-pvc
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-pvc
        persistentVolumeClaim:
          claimName: mysql-pvc

