apiVersion: v1
kind: Service
metadata:
  labels:
    app: php-service
  name: php-service
  annotations:
    metallb.universe.tf/adress-pool: default
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.99.103
  selector:
    app: php-pod
  ports:
  - name: php-ports
    protocol: TCP
    port: 5000
    targetPort: 5000
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-deployment
  labels:
    app: php-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-pod
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: php-pod
    spec:
      restartPolicy: Always
      containers:
      - image: my_php
        name: php
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        env:
        - name: WORDPRESS_DB_HOST
          valueFrom:
            configMapKeyRef:
              name: mysql-configmap
              key: wordpress-db-host
        - name: WORDPRESS_DB_NAME
          valueFrom:
            secretKeyRef:
              name: wp-mysql-php-secret
              key: wordpress-db-name
        - name: WORDPRESS_DB_USER
          valueFrom:
            secretKeyRef:
              name: wp-mysql-php-secret
              key: mysql-db-user
        - name: WORDPRESS_DB_PWD
          valueFrom:
            secretKeyRef:
              name: wp-mysql-php-secret
              key: mysql-db-pwd
