apiVersion: v1
kind: Service
metadata:
  labels:
    app: wordpress-service
  name: wordpress-service
  annotations:
    metallb.universe.tf/adress-pool: default
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.99.102
  selector:
    app: wordpress-pod
  ports:
  - name: wordpress-ports
    protocol: TCP
    port: 5050
    targetPort: 5050
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pv-claim
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
  labels:
    app: wordpress-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress-pod
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: wordpress-pod
    spec:
      restartPolicy: Always
      containers:
      - image: my_wordpress
        name: wordpress
        imagePullPolicy: Never
        env:
        - name: WORDPRESS_DB_HOST
          valueFrom:
            configMapKeyRef:
              name: mysql-configmap
              key: wordpress-db-host
        - name: WORDPRESS_DB_NAME
          valueFrom:
            secretKeyRef:
              name: wp-mysql-php-secret
              key: wordpress-db-name
        - name: WORDPRESS_DB_USER
          valueFrom:
            secretKeyRef:
              name: wp-mysql-php-secret
              key: mysql-db-user
        - name: WORDPRESS_DB_PWD
          valueFrom:
            secretKeyRef:
              name: wp-mysql-php-secret
              key: mysql-db-pwd
        ports:
        - containerPort: 5050
        volumeMounts:
        - name: wp-pv-claim
          mountPath: /usr/share/webapps/wordpress/wp-content/
      volumes:
      - name: wp-pv-claim
        persistentVolumeClaim:
          claimName: wp-pv-claim
