apiVersion: v1
kind: Service
metadata:
  labels:
    app: ftps
  name: ftps-service
  #annotations:
    #metallb.universe.tf/allow-shared-ip: "true"
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.99.104
  selector:
    app: ftps
  ports:
  - name: ftps
    protocol: TCP
    port: 21
    targetPort: 21
  - name: ftps2
    protocol: TCP
    port: 20
    targetPort: 20
  - name: ftps-data
    port: 30021
    protocol: TCP
    targetPort: 30021
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ftps-pvc
  labels:
    app: ftps-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---

apiVersion: apps/v1
kind: Deployment
metadata: 
  name: ftps-deployment
  labels:
    app: ftps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - image: my_ftps
        name: ftps
        imagePullPolicy: Never
        ports:
        - containerPort: 21
        - containerPort: 30021
        volumeMounts:
        - name: ftps-volume
          mountPath: /root/
      volumes:
      - name: ftps-volume
        persistentVolumeClaim:
          claimName: ftps-pvc


